# Generated by Django 4.2.7 on 2023-11-20 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField(max_length=240)),
                ('image', models.ImageField(upload_to='')),
                ('image_url', models.URLField()),
                ('date', models.DateField(auto_now=True)),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='myport.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['name'], name='myport_cate_name_08ffa4_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['id', 'slug'], name='myport_proj_id_392543_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['title'], name='myport_proj_title_65e40c_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['-date'], name='myport_proj_date_9fb9b1_idx'),
        ),
    ]
