# Generated by Django 4.2.7 on 2023-11-21 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0003_alter_project_image_alter_project_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Category',
            new_name='category',
        ),
    ]
