# Generated by Django 4.2.7 on 2023-11-21 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0006_project_git_source_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=240)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='projects/images')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['id', 'slug'], name='myport_post_id_6560a8_idx'), models.Index(fields=['title'], name='myport_post_title_d6638d_idx'), models.Index(fields=['-date'], name='myport_post_date_9f1344_idx')],
            },
        ),
    ]
