# Generated by Django 4.2.7 on 2023-11-21 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0007_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=440),
        ),
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
