# Generated by Django 4.2.7 on 2023-11-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0008_alter_post_title_alter_post_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='video_url',
        ),
        migrations.AddField(
            model_name='post',
            name='embed_code',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
