# Generated by Django 4.2.7 on 2023-11-22 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0009_remove_post_video_url_post_embed_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
