# Generated by Django 4.2.7 on 2023-11-24 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0010_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='embed_code',
            field=models.CharField(blank=True, max_length=550),
        ),
    ]
