# Generated by Django 4.2.7 on 2024-01-05 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0011_project_embed_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
