# Generated by Django 4.2.7 on 2024-01-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myport', '0012_project_website_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='git_source_code',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
