# Generated by Django 4.2.7 on 2023-11-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=440)),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True)),
                ('embed_code', models.CharField(blank=True, max_length=550)),
                ('image', models.ImageField(blank=True, upload_to='projects/images')),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
                'indexes': [models.Index(fields=['id', 'slug'], name='feed_post_id_b82c4a_idx'), models.Index(fields=['title'], name='feed_post_title_4f844e_idx'), models.Index(fields=['-date'], name='feed_post_date_47f2e7_idx')],
            },
        ),
    ]
